language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

install:
  - pip install --user -r numpy
  - pip install --user -r scipy
  - pip install --user -r networkx
  - pip install --user -r mlxtend
  - pip install --user -r sklearn

script:
  - python tests/stability_tests.py