language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

install:
  - pip install numpy
  - pip install scipy
  - pip install networkx
  - pip install mlxtend
  - pip install sklearn
  - pip install nose

script:
  - nosetests packman -a '!slow'