language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

cache: pip

install:
  - pip install numpy
  - pip install scipy
  - pip install networkx
  - pip install mlxtend
  - pip install sklearn
  - pip install py-packman

script:
  - python tests/stability_tests.py