# Use https://pypi.org/project/nose2pytest to migrate from nose to pytest
# `nose.tools.assert_equals()` will raise an AttributeError on Python >= 3.10.
# Notes: nose2pytest does not remove unused imports
#        nose2pytest does not fix assume_raises, raises which still function on Py3.10.
         
name: nose2pytest
on: [push, pull_request]
jobs:
  nose2pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install nose2pytest
    - run: nose2pytest -h
    - run: nose2pytest -v .
    - run: nose2pytest -w .
    - run: git diff  # Copy this command's output into a file and `git apply nose2pytest.patch`
    - run: grep -r nose .  # nose2pytest does NOT remove the now unused imports
