# Use https://pypi.org/project/nose2pytest to migrate from nose to pytest
# `nose.tools.assert_equals()` will raise an AttributeError on Python >= 3.10.
# Notes: nose2pytest does not remove unused imports
#        nose2pytest does not fix assume_raises, raises which still function on Py3.10.
         
name: nose2pytest
on: [push, pull_request]
jobs:
  nose2pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install git+https://github.com/pytest-dev/nose2pytest.git
    - run: nose2pytest --version ; nose2pytest -h
    - run: pip install -e .
    - run: nose2pytest -v .
    - run: nose2pytest -w .
    - run: nose2pytest -v packman/tests/
    - run: git diff  # Copy this command's output into a file and `git apply nose2pytest.patch`
    - run: grep -r nose .  # nose2pytest does NOT remove the now unused imports
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - run: pip install pytest
    - run: pytest --version ; pytest --help
    - run: pip install -e .
    - run: pytest
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user ruff
    - run: ruff --ignore=E402,E701,E711,E712,E722,E741,F401,F402,F403,F841
                --exit-zero --line-length=1100 --target-version=py37 --statistics . | sort -k 2
    - run: ruff --ignore=E402,E701,E711,E712,E722,E741,F401,F402,F403,F841
                --format=github --line-length=1100 --target-version=py37
